server:
  port: 8080

spring:
  application:
    name: chat-server
  datasource:
    url: jdbc:mysql://localhost:3306/chat
    username: root
    password: r1r2r3
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true